all:
	@make --no-print-directory clean
	@make --no-print-directory build
	@make --no-print-directory install

clean:force
	@echo "sub clean!"
	
build:force
	@echo "sub build!"

install:force
	@echo "sub install!"
force:
	@echo "sub force!"

include Makefile.include
