######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 23 13:59:29 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += helloworld.cpp

TRANSLATIONS += Language_Chn.ts
