// Class automatically generated by Dev-C++ New Class wizard

#include "myGraph.h" // class's header file

// class constructor
MyGraph::MyGraph()
{

}

// class destructor
MyGraph::~MyGraph()
{
	// insert your code here
}
void MyGraph::readGraph()
{
	//欠缺和合法性的检查
#if	DEBUGMYGRAPH == 1//调试状态下不用输入，麻烦
	ifstream infile("example.txt");
#else
	char filename[256];
	cout<<"请输入文件名(包含扩展名的txt文件):"<<endl;
	cin>>filename;
	ifstream infile(filename);
#endif
	if(!infile)
	{
		cout<<"文件不存在！请重新输入！";
		return;
	}

//把图初始化
#if	DEBUGMYGRAPH == 1
	for(int i = 0; i < N; i++)
	{
		Vertex[i].num = i;
		for(int j = 0; j < N; j++)
		{
			Edge[i][j].isVisited = 0;
			Edge[i][j].isE = 0;
		}
	}
#else
	for(int i = 0; i < n; i++)
	{
		Vertex[i].num = i;
		for(int j = 0; j < n; j++)
		{
			Edge[i][j].isVisited = 0;
			Edge[i][j].isE = 0;
		}
	}
#endif
	
	cout<<"开始读取文件..."<<endl;
	infile>>n;//得到图的顶点数
	int s,e;
	s = 0;
	e = 0;
	while(!infile.eof())
	{
		infile>>s;
		infile>>e;
		Vertex[s].k ++;
		//Vertex[e].k ++;
		Edge[s][e].isE = 1;
		Edge[s][e].isVisited = 0;
		//Edge[e][s].isE = 1;
		//Edge[e][s].isVisited = 0;
	}

#if DEBUGMYGRAPH !=1
	//Vertex = new
#endif
	cout<<"读取文件成功！"<<endl;
	infile.close();
}