######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 20 14:10:02 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myUIWidget.h
FORMS += untitled.ui
SOURCES += main.cpp myUIWidget.cpp
