######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 30 14:31:23 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myCallback.h
SOURCES += main.cpp myCallback.cpp
