// Class automatically generated by Dev-C++ New Class wizard
#include "myVertex.h"
// 堆栈
class StackNode
{
	public:
		// class constructor
		StackNode();
		// class destructor
		~StackNode();
		//路径 
		MyVertex1 vertex;
		//表示下一条将要尝试的边
		int next;
		//表示当前最新边的代价
		int curE; 
};

