######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 11 09:40:14 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myCallback.h
SOURCES += main.cpp myCallback.cpp
