all:
	@make --no-print-directory clean
	@make --no-print-directory build
	@make --no-print-directory install
	@make -C sub

clean:
	@echo "main clean!"
	
build:
	@echo "main build!"

install:
	@echo "main install!"
