######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 20 15:48:49 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += buttonClose.cpp
