######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 25 10:28:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lineeditdelegate.h mystringlistmodel.h
SOURCES += lineeditdelegate.cpp main.cpp mystringlistmode.cpp
