######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 20 13:13:43 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += untitled.ui
SOURCES += main.cpp
