######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 20 14:57:49 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

#Input
FORMS += untitled.ui
SOURCES += main.cpp

#lvkaiadd
FORMS -= untitled.ui
CONFIG += uitools
