list:winManage.c example_list.c
	gcc -o list winManage.c example_list.c `pkg-config --cflags --libs gtk+-2.0`
close_active:winManage.c example_closeActive.c
	gcc -o close_active winManage.c example_closeActive.c `pkg-config --cflags --libs gtk+-2.0`
